DEFAULT_USERNAME = 'admin'
DEFAULT_PASSWORD = 'admin123'

# 仪表盘提醒阈值
SUPPLEMENT_STOCKOUT_DAYS_THRESHOLD = 90  # 补剂断货提醒：90天
PACKAGING_STOCKOUT_DAYS_THRESHOLD = 35   # 包装用耗材断货提醒：35天
SUPPLEMENT_EXPIRY_DAYS_THRESHOLD = 360   # 补剂过期提醒：360天