name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # 监控 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}  # 在 GitHub Secrets 中设置
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/你的用户名/webapps/你的应用名/reload/ \
        -H "Authorization: Token $PA_API_TOKEN"
